addMenu("Demo", "demo-top");

addLink("demo-top", "&nbsp;Menu Item", "", "", "");
addSubMenu("demo-top", "&nbsp;Long & Scroll", "", "", "scroll-sub", "");
addSubMenu("demo-top", "&nbsp;Multi-Columns", "", "", "multi-sub", "");
addLink("demo-top", "&nbsp;Menu Item", "", "", "");
addLink("demo-top", "&nbsp;Menu Item", "", "", "");
addLink("demo-top", "&nbsp;Menu Item", "", "", "");
addLink("demo-top", "&nbsp;Menu Item", "", "", "");
addLink("demo-top", "&nbsp;Menu Item", "", "", "");
addLink("demo-top", "&nbsp;Menu Item", "", "", "");

addLink("scroll-sub", "&nbsp;Menu Item 1", "", "", "");
addLink("scroll-sub", "&nbsp;Menu Item 2", "", "", "");
addLink("scroll-sub", "&nbsp;Menu Item 3", "", "", "");
addLink("scroll-sub", "&nbsp;Menu Item 4", "", "", "");
addLink("scroll-sub", "&nbsp;Menu Item 5", "", "", "");
addLink("scroll-sub", "&nbsp;Menu Item 6", "", "", "");
addLink("scroll-sub", "&nbsp;Menu Item 7", "", "", "");
addLink("scroll-sub", "&nbsp;Menu Item 8", "", "", "");
addLink("scroll-sub", "&nbsp;Menu Item 9", "", "", "");
addLink("scroll-sub", "&nbsp;Menu Item 10", "", "", "");
addLink("scroll-sub", "&nbsp;Menu Item 11", "", "", "");
addLink("scroll-sub", "&nbsp;Menu Item 12", "", "", "");
addLink("scroll-sub", "&nbsp;Menu Item 13", "", "", "");
addLink("scroll-sub", "&nbsp;Menu Item 14", "", "", "");
addLink("scroll-sub", "&nbsp;Menu Item 15", "", "", "");
addLink("scroll-sub", "&nbsp;Menu Item 16", "", "", "");
addLink("scroll-sub", "&nbsp;Menu Item 17", "", "", "");
addLink("scroll-sub", "&nbsp;Menu Item 18", "", "", "");
addLink("scroll-sub", "&nbsp;Menu Item 19", "", "", "");
addLink("scroll-sub", "&nbsp;Menu Item 20", "", "", "");
addLink("scroll-sub", "&nbsp;Menu Item 21", "", "", "");
addLink("scroll-sub", "&nbsp;Menu Item 22", "", "", "");
addLink("scroll-sub", "&nbsp;Menu Item 23", "", "", "");
addLink("scroll-sub", "&nbsp;Menu Item 24", "", "", "");
addLink("scroll-sub", "&nbsp;Menu Item 25", "", "", "");
addLink("scroll-sub", "&nbsp;Menu Item 26", "", "", "");
addLink("scroll-sub", "&nbsp;Menu Item 27", "", "", "");
addLink("scroll-sub", "&nbsp;Menu Item 28", "", "", "");
addLink("scroll-sub", "&nbsp;Menu Item 29", "", "", "");
addLink("scroll-sub", "&nbsp;Menu Item 30", "", "", "");
addLink("scroll-sub", "&nbsp;Menu Item 31", "", "", "");
addLink("scroll-sub", "&nbsp;Menu Item 32", "", "", "");
addLink("scroll-sub", "&nbsp;Menu Item 33", "", "", "");
addLink("scroll-sub", "&nbsp;Menu Item 34", "", "", "");
addLink("scroll-sub", "&nbsp;Menu Item 35", "", "", "");
addLink("scroll-sub", "&nbsp;Menu Item 36", "", "", "");
addLink("scroll-sub", "&nbsp;Menu Item 37", "", "", "");
addLink("scroll-sub", "&nbsp;Menu Item 38", "", "", "");
addLink("scroll-sub", "&nbsp;Menu Item 39", "", "", "");
addLink("scroll-sub", "&nbsp;Menu Item 40", "", "", "");

addLink("multi-sub", "&nbsp;Menu Item 1", "", "", "");
addLink("multi-sub", "&nbsp;Menu Item 2", "", "", "");
addLink("multi-sub", "&nbsp;Menu Item 3", "", "", "");
addLink("multi-sub", "&nbsp;Menu Item 4", "", "", "");
addLink("multi-sub", "&nbsp;Menu Item 5", "", "", "");
addLink("multi-sub", "&nbsp;Menu Item 6", "", "", "");
addLink("multi-sub", "&nbsp;Menu Item 7", "", "", "");
addLink("multi-sub", "&nbsp;Menu Item 8", "", "", "");
addLink("multi-sub", "&nbsp;Menu Item 9", "", "", "");
addLink("multi-sub", "&nbsp;Menu Item 10", "", "", "");
addLink("multi-sub", "&nbsp;Menu Item 11", "", "", "");
addLink("multi-sub", "&nbsp;Menu Item 12", "", "", "");
addLink("multi-sub", "&nbsp;Menu Item 13", "", "", "");
addLink("multi-sub", "&nbsp;Menu Item 14", "", "", "");
addLink("multi-sub", "&nbsp;Menu Item 15", "", "", "");
addLink("multi-sub", "&nbsp;Menu Item 16", "", "", "");
addLink("multi-sub", "&nbsp;Menu Item 17", "", "", "");
addLink("multi-sub", "&nbsp;Menu Item 18", "", "", "");
addLink("multi-sub", "&nbsp;Menu Item 19", "", "", "");
addLink("multi-sub", "&nbsp;Menu Item 20", "", "", "");
addLink("multi-sub", "&nbsp;Menu Item 21", "", "", "");
addLink("multi-sub", "&nbsp;Menu Item 22", "", "", "");
addLink("multi-sub", "&nbsp;Menu Item 23", "", "", "");
addLink("multi-sub", "&nbsp;Menu Item 24", "", "", "");
addLink("multi-sub", "&nbsp;Menu Item 25", "", "", "");
addLink("multi-sub", "&nbsp;Menu Item 26", "", "", "");
addLink("multi-sub", "&nbsp;Menu Item 27", "", "", "");
addLink("multi-sub", "&nbsp;Menu Item 28", "", "", "");
addLink("multi-sub", "&nbsp;Menu Item 29", "", "", "");
addLink("multi-sub", "&nbsp;Menu Item 30", "", "", "");
addLink("multi-sub", "&nbsp;Menu Item 31", "", "", "");
addLink("multi-sub", "&nbsp;Menu Item 32", "", "", "");
addLink("multi-sub", "&nbsp;Menu Item 33", "", "", "");
addLink("multi-sub", "&nbsp;Menu Item 34", "", "", "");
addLink("multi-sub", "&nbsp;Menu Item 35", "", "", "");
addLink("multi-sub", "&nbsp;Menu Item 36", "", "", "");
addLink("multi-sub", "&nbsp;Menu Item 37", "", "", "");
addLink("multi-sub", "&nbsp;Menu Item 38", "", "", "");
addLink("multi-sub", "&nbsp;Menu Item 39", "", "", "");
addLink("multi-sub", "&nbsp;Menu Item 40", "", "", "");

endMenu();
