addMenu("Demo", "demo-top");
addSubMenu("demo-top", "Data", "", "", "2-sub", "");
addSubMenu("demo-top", "Price Guideline", "", "", "3-sub", "");
addSubMenu("demo-top", "Quotation", "", "", "4-sub", "");
addSubMenu("demo-top", "Setting", "", "", "5-sub", "");
 addLink("demo-top", "Exit", "", "close.asp", "");
addLink("2-sub", "Search Configuration", "", "configuration/configuration_search.asp", "");
addLink("2-sub", "3rd Party Product", "", "configuration/party_search.asp", "");
addLink("2-sub", "Upload Configuration", "", "configuration/configuration_upload.asp", "");
addLink("2-sub", "Upload 3rd Party", "", "configuration/party_upload.asp", "");
addLink("2-sub", "Search Modality", "", "configuration/modality_search.asp", "");
addLink("2-sub", "Upload Modality", "", "configuration/modality_upload.asp", "");
addLink("2-sub", "Exchange Rate", "", "system/exchanges.asp", "");
addLink("3-sub", "Price Guideline", "", "product/product_search.asp", "");
addLink("3-sub", "Publish", "", "product/product_publish.asp", "");
addLink("4-sub", "Quotation Maker", "", "quotation/quotationList.asp", "");
addLink("5-sub", "User", "", "system/userManager.asp", "");
addLink("5-sub", "Role", "", "system/roleManager.asp", "");
addLink("5-sub", "Function", "", "system/functionManager.asp", "");
addLink("5-sub", "Change Password", "", "system/password.asp", "");
endMenu();
